import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Waseem Akram",
  description: "Terms of service for waseemmalikdev.eu.cc",
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen py-16 px-6 lg:px-16">
      <div className="max-w-3xl mx-auto">

        {/* Back */}
        <div className="mb-14">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-[13px] text-[#555] hover:text-white transition-colors duration-200 group"
          >
            <svg className="size-4 group-hover:-translate-x-0.5 transition-transform duration-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 12H5M12 5l-7 7 7 7" />
            </svg>
            Back to home
          </Link>
        </div>

        {/* Header */}
        <div className="pb-8 mb-12 border-b border-white/10">
          <h1 className="text-[clamp(36px,5vw,64px)] font-bold text-white leading-none tracking-[-0.03em] mb-4">
            Terms of Service
          </h1>
          <p className="text-[13px] text-[#444] font-mono">Last updated: January 2026</p>
        </div>

        {/* Content */}
        <div className="space-y-12 text-[15px] text-[#888] leading-[1.85] font-light">

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">1. Acceptance of Terms</h2>
            <p>
              By accessing and using waseemmalikdev.eu.cc ("the website"), you accept and agree to be
              bound by these Terms of Service. If you do not agree to these terms, please do not use
              this website.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">2. Use of the Website</h2>
            <p>This website is a personal portfolio showcasing the work and services of Waseem Akram. You agree to use this site only for lawful purposes and in a manner that does not:</p>
            <ul className="space-y-2 pl-5 list-disc text-[#777]">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on the intellectual property rights of others</li>
              <li>Transmit harmful, offensive, or disruptive content</li>
              <li>Attempt to gain unauthorised access to any part of the site</li>
              <li>Interfere with the proper functioning of the website</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">3. Intellectual Property</h2>
            <p>
              All content on this website — including but not limited to text, code, design, images,
              and project descriptions — is the intellectual property of Waseem Akram unless
              otherwise stated.
            </p>
            <p>
              You may not reproduce, distribute, or use any content from this website without
              prior written permission. Sharing links to this website is permitted and encouraged.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">4. Freelance & Project Enquiries</h2>
            <p>
              Any project enquiries submitted through the contact form or chatbot are not legally
              binding. A formal agreement, scope of work, and payment terms will be established
              separately before any work begins.
            </p>
            <p>
              I reserve the right to decline any project enquiry at my discretion.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">5. AI Chatbot</h2>
            <p>
              This website includes an AI-powered chatbot assistant. Responses generated by the chatbot
              are for informational purposes only. They do not constitute professional advice,
              contractual obligations, or guarantees of any kind.
            </p>
            <p>
              The chatbot may occasionally produce inaccurate responses. Always verify important
              information directly with me via email.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">6. Third-Party Links</h2>
            <p>
              This website may contain links to third-party websites (GitHub, LinkedIn, live project
              demos, etc.). These links are provided for convenience only. I have no control over
              the content of those sites and accept no responsibility for them.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">7. Disclaimer of Warranties</h2>
            <p>
              This website is provided "as is" without any warranties, express or implied. I do not
              warrant that the website will be error-free, uninterrupted, or free of harmful components.
            </p>
            <p>
              I make no representations about the accuracy or completeness of the content on this site.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Waseem Akram shall not be liable for any
              indirect, incidental, or consequential damages arising from your use of this website
              or any content contained within it.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">9. Changes to Terms</h2>
            <p>
              I reserve the right to update these terms at any time. Changes will be posted on this
              page with an updated date. Continued use of the website after changes constitutes
              your acceptance of the revised terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-[18px] font-semibold text-white tracking-[-0.01em]">10. Contact</h2>
            <p>
              If you have any questions about these terms, please reach out at{" "}
              <a
                href="mailto:malikwaseemshzad@gmail.com"
                className="text-white underline underline-offset-4 decoration-white/30 hover:decoration-white/70 transition-all"
              >
                malikwaseemshzad@gmail.com
              </a>
            </p>
          </section>

        </div>

        {/* Footer */}
        <div className="mt-20 pt-8 border-t border-white/8 flex items-center justify-between flex-wrap gap-4">
          <p className="text-[12px] text-[#333] font-mono">© 2026 Waseem Akram</p>
          <Link
            href="/privacy"
            className="text-[12px] text-[#444] hover:text-white transition-colors duration-150"
          >
            Privacy Policy →
          </Link>
        </div>

      </div>
    </main>
  );
}